grafana:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.localhost
    paths:
      - /

prometheus:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - prometheus.localhost
    paths:
      - /
