apiVersion: v1
kind: Service
metadata:
  name: cats-gazing-postgres
  namespace: application
spec:
  selector:
    app: cats-gazing-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432